### ISSUE TITLE
How return error when a key does not exist?

### ISSUE THREAD

**Issue by pengyu** [0k/shyaml#10]
Suppose that I have the following `test.yaml` file.

```
name: "MyName !!"
subvalue:
    how-much: 1.1
    things:
        - first
        - second
        - third
    other-things: [a, b, c]
    maintainer: "Valentin Lab"
    description: |
        Multiline description:
        Line 1
        Line 2
```

The following command would return an exit status of 0 event the key `subvalue.maintainer1` does not exist. Is there a way to have shyaml return an non-zero status in such a case? Thanks.

```
~$ cat test.yaml | shyaml get-value subvalue.maintainer1
~$ echo $?
0
```
