### ISSUE TITLE
Can not read subvalue of subvalue

### ISSUE THREAD

**Issue by GiovanniAffogbolo** [0k/shyaml#64]
Hello,

I found this tool (shyaml) and i have an issue using the function above : 

**test.yaml**
```
people:
  Thomas:
    age: 15
    sex: M
  Laura:
    age: 15
    sex: F
```

**Script bash :** 
`echo test.yaml | shyaml get-value people.Thomas.age`

Executing this does not work. As if shyaml only read on the two first levels.
Is it me who doesn't understand it properly or is true ? Is there a fix for this ? Thanks in advance.
